FROM node:20-alpine AS build

WORKDIR /app

ARG REACT_APP_BACKEND_URL
ARG REACT_APP_ADMIN_KEY
ARG REACT_APP_GAME_SERVER_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
ENV REACT_APP_ADMIN_KEY=$REACT_APP_ADMIN_KEY
ENV REACT_APP_GAME_SERVER_URL=$REACT_APP_GAME_SERVER_URL

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
